# BASE UI
ColorColumn: '- cursorLine'
Conceal: '-'
Cursor: 'pureBlack foreground'
CursorIM: '@Cursor'
CursorColumn: '- cursorLine'
CursorLine: '- cursorLine'
CursorLineNr: 'foreground cursorLine'
Directory: 'lightPink -'
DiffAdd: 'lightBlue visualSel'
DiffChange: 'gitGreen visualSel'
DiffDelete: 'red visualSel'
DiffText: 'lightBlue visualSel'
ErrorMsg: 'red'
VertSplit: 'yellow background'
Folded: 'cursorLine background'
FoldColumn: 'cursorLine background'
SignColumn: 'midPurple background'
IncSearch: 'foreground midPurple'
LineNr: 'darkBlue background'
MatchParen: 'foreground cursorLine'
ModeMsg: 'lightPink' # foreground  insert/visual/etc.
MoreMsg: '@ModeMsg'
Normal: 'foreground background'
PMenu: 'foreground grey'
PMenuSel: 'foreground lightGrey'
PmenuSbar: '- yellow'
PmenuThumb: '- lightGrey'
Question: '@ModeMsg'
Search: '- midBlue'
SpecialKey: 'foreground background'
SpellBad: '- - u'
SpellLocal: '- - u'
SpellCap: 'lightBlue - u'
SpellRare: 'gitGreen - u'
StatusLine: 'grey yellow'
StatusLineNC: 'foreground background'
TabLine: 'lightGrey background i' 
TabLineFill: 'background background' # unselected tab
TabLineSel: 'background lightPink b'
Title: '@ModeMsg'
Visual: '- visualSel'
VisualNOS: '@Visual'
WarningMsg: 'orange background'
WildMenu: 'foreground grey'
EndOfBuffer: 'background background'
NonText: 'background background'
# BASE SYNTAX
Comment: 'midPurple -'
Constant: 'yellow'
String: 'orange - i' # Constant
Character: '@Constant' # Constant
Boolean: 'mutedBlue' # Constant
Number: 'orange' # Constant
Float: '@Number' # Constant
Identifier: 'lightBlue'
Function: 'lightBlue' # Identifier
Statement: 'yellow'
Conditional: 'orange' # Statement
Repeat: 'yellow' # Statement
Label: 'yellow' # Statement
Operator: 'berryPink' # Statement
Keyword: 'yellow' # Statement
Exception: 'yellow' # Statement
PreProc: 'lightPink'
Include: 'lightPink' # PreProc
Define: 'yellow' # PreProc
Macro: '@PreProc' # PreProc
PreCondit: '@PreProc' # PreProc
Type: 'yellow'
StorageClass: 'berryPink' # Type
Structure: '@Type' # Type
Typedef: '@lightPink' # Type
Special: 'orange'
SpecialChar: '@Special' # Special
Tag: '@Special' # Special
Delimiter: 'orange' # Special
SpecialComment: '@Special' # Special
Debug: '@Special' # Special
Underlined: 'foreground background u'
Ignore: 'red'
Error: 'red'
Todo: 'gitGreen'



# python
pythonStatement: 'yellow' # Statement
pythonConditional: 'orange' # Conditional
pythonRepeat: 'orange' # Repeat
pythonOperator: 'berryPink' # Operator
pythonException: 'yellow' # Exception
pythonInclude: 'yellow' # Include
pythonDecorator: 'lightBlue' # Define
pythonFunction: 'lightBlue' # Function
pythonComment: 'midPurple - i' # Comment
pythonTodo: 'gitGreen' # Todo
pythonString: '@String' # String
pythonRawString: '@String' # String
pythonQuotes: 'orange' # String
pythonTripleQuotes: 'midPurple' # pythonQuotes
pythonEscape: 'mutedBlue' # Special
pythonNumber: 'orange' # Number
pythonBuiltin: 'berryPink - i' # Function
pythonExceptions: '@pythonException' # Structure
pythonSpaceError: 'berryPink background u' # Error
pythonDoctest: 'midPurple' # Special
pythonDoctestValue: 'lightPink' # Define



# html
htmlTag: 'foreground' # Function
htmlEndTag: '@htmlTag' # Identifier
htmlArg: 'lightPink' # Type
htmlTagName: 'mutedBlue' # htmlStatement
htmlValue: 'lightBlue' # String
htmlH1: 'berryPink' # Title
htmlH2: 'lightPink' # htmlH1
htmlH3: 'lightPink' # htmlH2
htmlH4: 'lightPink' # htmlH3
htmlH5: 'lightPink' # htmlH4
htmlH6: 'lightPink' # htmlH5
htmlHead: '@htmlTag' # PreProc
htmlTitle: 'yellow' # Title
htmlBoldItalicUnderline: 'lightPink' # htmlBoldUnderlineItalic
htmlUnderlineBold: 'lightPink' # htmlBoldUnderline
htmlUnderlineItalicBold: 'lightPink' # htmlBoldUnderlineItalic
htmlUnderlineBoldItalic: 'lightPink' # htmlBoldUnderlineItalic
htmlItalicUnderline: 'lightPink' # htmlUnderlineItalic
htmlItalicBold: 'lightPink' # htmlBoldItalic
htmlItalicBoldUnderline: 'lightPink' # htmlBoldUnderlineItalic
htmlItalicUnderlineBold: 'lightPink' # htmlBoldUnderlineItalic
htmlLink: 'gitGreen' # Underlined
htmlString: 'orange' # String
htmlComment: 'midPurple' # Comment
htmlCssStyleComment: '@htmlComment' # Comment



#yaml
yamlTodo: 'lightPink' # Todo
yamlString: 'lightPink' # String
yamlFlowString: 'foreground' # yamlString
yamlFlowStringDelimiter: 'lightPink' # yamlString
yamlKeyValueDelimiter: 'berryPink' # Special
yamlConstant: 'midBlue' # Constant
yamlBool: 'orange' # yamlConstant
yamlAnchor: 'midPurple' # Type
yamlAlias: 'foreground' # Type
yamlNodeTag: 'foreground' # Type
yamlInteger: 'orange' # Number
yamlFloat: 'orange' # Float
yamlTimestamp: 'gitGreen' # Number

#javascript
javaScriptComment: '- - i' # Comment
javaScriptLineComment: '- - i' # Comment
javaScriptCommentTodo: '' # Todo
javaScriptSpecial: '' # Special
javaScriptStringS: '- - i' # String
javaScriptStringD: '- - i' # String
javaScriptCharacter: '' # Character
javaScriptSpecialCharacter: '' # javaScriptSpecial
javaScriptNumber: '' # javaScriptValue
javaScriptConditional: 'orange' # Conditional
javaScriptRepeat: '' # Repeat
javaScriptBranch: 'orange' # Conditional
javaScriptOperator: '' # Operator
javaScriptType: 'berryPink' # Type
javaScriptStatement: '' # Statement
javaScriptFunction: '' # Function
javaScriptBraces: '' # Function
javaScriptError: '' # Error
javaScriptParensError: '' # Error
javaScriptNull: '' # Keyword
javaScriptBoolean: 'berryPink - i' # Boolean
javaScriptRegexpString: '' # String
javaScriptIdentifier: '' # Identifier
javaScriptLabel: 'gitGreen' # Label
javaScriptException: '' # Exception
javaScriptMessage: '' # Keyword
javaScriptGlobal: '' # Keyword
javaScriptMember: '' # Keyword
javaScriptDeprecated: '' # Exception
javaScriptReserved: '' # Keyword
javaScriptDebug: '' # Debug
javaScriptConstant: 'yellow background i' # Label



#CSS
cssComment: '' # Comment
cssVendor: '' # Comment
cssHacks: '' # Comment
cssTagName: 'yellow' # Statement
cssDeprecated: '' # Error
cssSelectorOp: 'orange' # Special
cssSelectorOp2: '' # Special
cssAttrComma: 'midBlue' # Special
cssAnimationProp: '' # cssProp
cssBackgroundProp: '' # cssProp
cssBorderProp: '' # cssProp
cssBoxProp: '' # cssProp
cssColorProp: '' # cssProp
cssContentForPagedMediaProp: '' # cssProp
cssDimensionProp: '' # cssProp
cssFlexibleBoxProp: '' # cssProp
cssFontProp: '' # cssProp
cssGeneratedContentProp: '' # cssProp
cssGridProp: '' # cssProp
cssHyerlinkProp: '' # cssProp
cssLineboxProp: '' # cssProp
cssListProp: '' # cssProp
cssMarqueeProp: '' # cssProp
cssMultiColumnProp: '' # cssProp
cssPagedMediaProp: '' # cssProp
cssPositioningProp: '' # cssProp
cssPrintProp: '' # cssProp
cssRubyProp: '' # cssProp
cssSpeechProp: '' # cssProp
cssTableProp: '' # cssProp
cssTextProp: '' # cssProp
cssTransformProp: '' # cssProp
cssTransitionProp: '' # cssProp
cssUIProp: '' # cssProp
cssIEUIProp: '' # cssProp
cssAuralProp: '' # cssProp
cssRenderProp: '' # cssProp
cssMobileTextProp: '' # cssProp
cssAnimationAttr: '' # cssAttr
cssBackgroundAttr: '' # cssAttr
cssBorderAttr: '' # cssAttr
cssBoxAttr: '' # cssAttr
cssContentForPagedMediaAttr: '' # cssAttr
cssDimensionAttr: '' # cssAttr
cssFlexibleBoxAttr: '' # cssAttr
cssFontAttr: '' # cssAttr
cssGeneratedContentAttr: '' # cssAttr
cssGridAttr: '' # cssAttr
cssHyerlinkAttr: '' # cssAttr
cssLineboxAttr: '' # cssAttr
cssListAttr: '' # cssAttr
cssMarginAttr: '' # cssAttr
cssMarqueeAttr: '' # cssAttr
cssMultiColumnAttr: '' # cssAttr
cssPaddingAttr: '' # cssAttr
cssPagedMediaAttr: '' # cssAttr
cssPositioningAttr: '' # cssAttr
cssGradientAttr: '' # cssAttr
cssPrintAttr: '' # cssAttr
cssRubyAttr: '' # cssAttr
cssSpeechAttr: '' # cssAttr
cssTableAttr: '' # cssAttr
cssTextAttr: '' # cssAttr
cssTransformAttr: '' # cssAttr
cssTransitionAttr: '' # cssAttr
cssUIAttr: '' # cssAttr
cssIEUIAttr: '' # cssAttr
cssAuralAttr: '' # cssAttr
cssRenderAttr: '' # cssAttr
cssCommonAttr: '' # cssAttr
cssPseudoClassId: '' # PreProc
cssPseudoClassLang: '' # Constant
cssValueLength: 'orange' # Number
cssValueInteger: 'orange' # Number
cssValueNumber: 'orange' # Number
cssValueAngle: '' # Number
cssValueTime: '' # Number
cssValueFrequency: '' # Number
cssFunction: '' # Constant
cssURL: '' # String
cssFunctionName: 'lightBlue' # Function
cssFunctionComma: '@cssAttrComma' # Function
cssColor: 'gitGreen' # Constant
cssIdentifier: 'lightBlue' # Function
cssInclude: '' # Include
cssIncludeKeyword: '' # atKeyword
cssImportant: '' # Special
cssBraces: 'berryPink - b' # Function
cssBraceError: '' # Error
cssError: '' # Error
cssUnicodeEscape: '' # Special
cssStringQQ: '' # String
cssStringQ: '' # String
cssAttributeSelector: '' # String
cssMedia: '' # atKeyword
cssMediaType: '' # Special
cssMediaComma: '@cssAttrComma' # Normal
cssMediaKeyword: '' # Statement
cssMediaProp: '' # cssProp
cssMediaAttr: '' # cssAttr
cssPage: '' # atKeyword
cssPagePseudo: '' # PreProc
cssPageMargin: '' # atKeyword
cssPageProp: '' # cssProp
cssKeyFrame: '' # atKeyword
cssKeyFrameSelector: '' # Constant
cssFontDescriptor: '' # Special
cssFontDescriptorFunction: '' # Constant
cssFontDescriptorProp: '' # cssProp
cssFontDescriptorAttr: '' # cssAttr
cssUnicodeRange: '' # Constant
cssClassName: 'lightBlue' # Function (Changed)
cssClassNameDot: 'mutedBlue' # Function
cssProp: 'foreground - i' # StorageClass
cssAttr: '' # Constant
cssUnitDecorators: 'orange' # Number
cssNoise: '' # Noise
atKeyword: '' # PreProc


# Nvim-tree
NvimTreeNormal: 'foreground menuPurple'
NvimTreeEndOfBuffer: 'menuPurple menuPurple'
